CREATE TABLE EMPLOYEE(ID INT PRIMARY KEY AUTO_INCREMENT, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), EMAIL VARCHAR(50), PHONE VARCHAR(20));

INSERT INTO EMPLOYEE (FIRSTNAME, LASTNAME, EMAIL, PHONE) VALUES ('Nilesh', 'Chauhan', 'nilesh.chauhan@sanelib.com', '123456789')